# Generated by Django 3.0.2 on 2020-02-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_disorder_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disorder',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='content',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
