# Generated by Django 3.0.2 on 2020-02-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200218_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='disorder',
            name='url_pattern',
            field=models.CharField(default='wip', max_length=30),
            preserve_default=False,
        ),
    ]
