# Generated by Django 3.0.2 on 2020-02-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_disorder_url_pattern'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disorder',
            old_name='content',
            new_name='details',
        ),
    ]
