# Generated by Django 3.0.5 on 2020-04-28 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='disorder',
            field=models.ForeignKey(default=62, on_delete=django.db.models.deletion.CASCADE, to='app.Disorder'),
            preserve_default=False,
        ),
    ]
