# Generated by Django 3.0.5 on 2020-04-28 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_testimony_disorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='disorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Disorder'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='disorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Disorder'),
        ),
    ]
