# Generated by Django 3.0.5 on 2020-04-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200428_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.IntegerField(choices=[(0, 'Requête envoyée.'), (1, 'Requête acceptée, un utilisateur va vous contacter !'), (2, "Session d'échange à venir."), (3, 'Rendez-vous terminé, requête archivée.')], default=0),
        ),
    ]
