# Generated by Django 2.2.12 on 2020-05-23 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='awareness_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='raise_awareness_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(choices=[(0, 'Requête envoyée.'), (1, "Requête acceptée, session d'échange à venir."), (3, 'Rendez-vous terminé, requête archivée.')], default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='want_to_understand_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
